### ISSUE TITLE
Functionality @user

### ISSUE THREAD

**Issue by lcasanova78** [taqueci/redmine_wysiwyg_editor#120]
When mentioning a project member by using the phrase @user_name, it is converted to a meaningless text user#<userid>, What's the point of this, if it were a link to the user's id it would be great, but just plain text I don't understand what it's for.
Could you explain me this functionality and how to take advantage of it?

**Comment by martincizek** [comment]
> When mentioning a project member by using the phrase @user_name, it is converted to a meaningless text user#, What's the point of this, if it were a link to the user's id it would be great, but just plain text I don't understand what it's for.

I guess should have been the `user#ID` user link syntax described [here](https://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingMarkdown#Redmine-links).

In genreal, an issue might be that once the user link is interpreted by Redmine formatter, it's difficult to restore the former syntax.

I'd vote for using `@username` as the default syntax. @taqueci ?

Can provide a PR later.

**Comment by taqueci** [comment]
Hi @lcasanova78 and @martincizek 

Using `user#ID` is for user privacy.
Jean-Philippe Lang, the author of Redmine, said user login name should be hidden. I think so too.

However, I understand your suggestion because syntax `@USERNAME` is well known and used by many applications.

> Can provide a PR later.

Thank you for your contribution!
I would be glad if `@USERNAME` is available only in non-pubilc project or using `@USERNAME` is configurable.

**Comment by lcasanova78** [comment]
But it is supposed to convert @username to a user # iduser link, but it does not create a link just plain text
