### ISSUE TITLE
Visual editor Support redmine_embedded_video plugin

### ISSUE THREAD

**Issue by kay54068** [taqueci/redmine_wysiwyg_editor#79]
How can I implement the redmine_embedded_video plugin macro from visual editor?

The redmine_embedded_video information:
https://github.com/cforce/redmine_embedded_video

**Comment by taqueci** [comment]
Hi @kay54068 

I want to implment macro input method on visual mode.
However, I have no good idea because each macro has its own usage.

As metioned in issue #56, you need to implement:

1. Custom menu and dialog to input macro
2. Convertion to Textile/Markdown
3. Convertion to visual mode content

You can add menu and dialog by:

* https://www.tiny.cloud/docs-4x/api/tinymce/tinymce.editor/#addbutton
* https://www.tiny.cloud/docs-4x/advanced/creating-custom-dialogs/#dialogsashtmlpages

I hope you can make it.
